// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRecords.Data;

namespace StudentRecords.Migrations
{
    [DbContext(typeof(RecordsContext))]
    [Migration("20181126080655_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentRecords.Models.Results", b =>
                {
                    b.Property<string>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Ass1Score");

                    b.Property<short>("Ass2Score");

                    b.Property<short>("ExamScore");

                    b.Property<short>("Semester");

                    b.Property<string>("UnitCode")
                        .IsRequired();

                    b.Property<short>("Year");

                    b.HasKey("StudentId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("StudentRecords.Models.Units", b =>
                {
                    b.Property<string>("UnitCode");

                    b.Property<string>("UnitCoordinator")
                        .IsRequired();

                    b.Property<string>("UnitOutline")
                        .IsRequired();

                    b.Property<string>("UnitTitle")
                        .IsRequired();

                    b.HasKey("UnitCode");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("StudentRecords.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudentRecords.Models.Units", b =>
                {
                    b.HasOne("StudentRecords.Models.Results", "Results")
                        .WithMany("Unit")
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
